(() => {
'use strict';

const STORE='tinos.workplace.data.v1';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>`${Date.now().toString(36)}${Math.random().toString(36).slice(2,8)}`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const fmt=v=>v?new Date(`${v}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'Not set';
const clone=v=>JSON.parse(JSON.stringify(v));
const cleanList=v=>String(v||'').split(/[,\n]/).map(x=>x.trim()).filter(Boolean);
const uniq=a=>[...new Set((a||[]).filter(Boolean))];

const blank={settings:{employerName:'',company:''},apprentices:[],learning:[],witnesses:[],oneToOnes:[],actions:[],updates:[]};
function load(){try{const x=JSON.parse(localStorage.getItem(STORE)||'null');return x&&typeof x==='object'?{...clone(blank),...x,settings:{...blank.settings,...(x.settings||{})}}:clone(blank)}catch{return clone(blank)}}
let state=load();
let currentId=null;

const screen=$('#screen'),tinos=$('#tinos'),speech=$('#tinosSpeech'),contextTitle=$('#contextTitle'),pillStack=$('#pillStack'),back=$('#backButton'),menu=$('#menuButton'),tools=$('#toolsMenu'),overlay=$('#overlayPanel'),title=$('#overlayTitle'),subtitle=$('#overlaySubtitle'),kicker=$('#overlayKicker'),content=$('#overlayContent');

function save(){localStorage.setItem(STORE,JSON.stringify(state));homeMetrics()}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function say(text){speech.textContent=text;tinos.classList.add('wobble');setTimeout(()=>tinos.classList.remove('wobble'),900)}
function blink(){tinos.classList.add('blink');setTimeout(()=>tinos.classList.remove('blink'),150)}
function greeting(){say(state.settings.employerName?`Hi ${state.settings.employerName}. What do you want to do?`:'Hi. What do you want to do?')}
function openOverlay(t,s='',k='TINOS'){tools.classList.remove('open');menu.setAttribute('aria-expanded','false');title.textContent=t;subtitle.textContent=s;kicker.textContent=k;overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');back.classList.add('show');content.innerHTML=''}
function closeOverlay(){overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true');content.innerHTML='';back.classList.toggle('show',screen.classList.contains('active'))}
function activate(){screen.classList.add('active');contextTitle.textContent='Employer · Workplace · Apprentice Support';contextTitle.classList.add('has-title');pillStack.innerHTML=[['My Apprentices','what can I help them do next?','apprentices'],['Workplace Learning','record or confirm learning','learning'],['Witness Evidence','verified employer evidence','witness'],['1-to-1s','quick development conversations','one-to-ones'],['Progress & Actions','gaps, opportunities and targets','actions'],['Share / Scan','QR-ready data exchange','exchange']].map(x=>`<button class="pill" data-open="${x[2]}"><strong>${x[0]}</strong><span>${x[1]}</span></button>`).join('');setTimeout(()=>pillStack.classList.add('ready'),100);back.classList.add('show');say('What do you want to work on?')}
function deactivate(){screen.classList.remove('active');pillStack.classList.remove('ready');contextTitle.classList.remove('has-title');contextTitle.textContent='';back.classList.remove('show');greeting()}
function homeMetrics(){$('#apprenticeCount').textContent=state.apprentices.length;$('#learningCount').textContent=state.learning.length;$('#witnessCount').textContent=state.witnesses.length;$('#actionCount').textContent=state.actions.filter(a=>a.status!=='complete').length}

function getApprentice(id){return state.apprentices.find(a=>a.id===id)}
function learningFor(id){return state.learning.filter(x=>x.apprenticeId===id)}
function witnessFor(id){return state.witnesses.filter(x=>x.apprenticeId===id)}
function oneToOnesFor(id){return state.oneToOnes.filter(x=>x.apprenticeId===id)}
function actionsFor(id){return state.actions.filter(x=>x.apprenticeId===id)}
function areaSet(records){return uniq(records.flatMap(r=>r.areas||[]))}
function workplaceAreas(id){return areaSet([...learningFor(id),...witnessFor(id)])}
function opportunities(a){const done=new Set(workplaceAreas(a.id).map(x=>x.toLowerCase()));const taught=uniq(a.taughtAreas||[]);const targets=uniq(a.targets||[]);return uniq([...taught.filter(x=>!done.has(x.toLowerCase())),...targets.filter(x=>!done.has(x.toLowerCase()))]).slice(0,6)}
function progressSummary(a){const done=workplaceAreas(a.id).length,opp=opportunities(a).length,open=actionsFor(a.id).filter(x=>x.status!=='complete').length;return `${done} workplace areas · ${opp} opportunities · ${open} actions`}
function marker(){return '<span class="marker"><i></i>Employer/workplace evidence</span>'}

function openView(view){if(view==='apprentices')renderApprentices();if(view==='learning')renderLearning();if(view==='witness')renderWitnesses();if(view==='one-to-ones')renderOneToOnes();if(view==='actions')renderActions();if(view==='exchange')renderExchange();if(view==='settings')renderSettings()}

function renderApprentices(){openOverlay('My Apprentices','Keep the workplace view simple: what is going well, what needs experience, and what should happen next.');content.innerHTML=`<div class="button-row"><button class="primary" data-add>+ Add apprentice</button><button class="secondary" data-import>Import update</button></div><div class="section-head"><h2>${state.apprentices.length} apprentice${state.apprentices.length===1?'':'s'}</h2><span>Stored locally</span></div>${state.apprentices.length?`<div class="list">${state.apprentices.map(a=>`<button class="list-button" data-apprentice="${a.id}"><span class="list-copy"><strong>${esc(a.name)}</strong><span>${esc(a.course||'Course not added')} · ${esc(progressSummary(a))}</span></span><span class="chip">Open</span></button>`).join('')}</div>`:`<div class="empty"><strong>No apprentices yet</strong><span>Add one manually or import a learner update from Evia/Nisia.</span></div>`}`;$('[data-add]').onclick=()=>apprenticeForm();$('[data-import]').onclick=()=>renderExchange('import');$$('[data-apprentice]').forEach(b=>b.onclick=()=>renderApprentice(b.dataset.apprentice))}
function apprenticeForm(existing=null){const a=existing?clone(existing):{id:uid(),name:'',reference:'',course:'',startDate:'',endDate:'',progress:null,taughtAreas:[],assessedAreas:[],targets:[]};openOverlay(existing?'Edit apprentice':'Add apprentice','Tinos only needs the workplace information the employer actually uses.','APPRENTICE');content.innerHTML=`<form id="apprenticeForm"><div class="card"><div class="form-grid"><label class="field full"><span>Apprentice name</span><input name="name" value="${esc(a.name)}" required></label><label class="field"><span>Reference / ID</span><input name="reference" value="${esc(a.reference||'')}"></label><label class="field"><span>Course</span><input name="course" value="${esc(a.course||'')}"></label><label class="field"><span>Start date</span><input type="date" name="startDate" value="${esc(a.startDate||'')}"></label><label class="field"><span>End date</span><input type="date" name="endDate" value="${esc(a.endDate||'')}"></label><label class="field full"><span>Recently taught / covered at college</span><textarea name="taught" placeholder="One area per line or comma separated">${esc((a.taughtAreas||[]).join('\n'))}</textarea></label><label class="field full"><span>Current workplace targets</span><textarea name="targets" placeholder="One area per line or comma separated">${esc((a.targets||[]).join('\n'))}</textarea></label></div></div><div class="button-row"><button class="primary">Save apprentice</button>${existing?'<button class="danger" type="button" data-delete>Delete</button>':''}</div></form>`;$('#apprenticeForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);a.name=String(f.get('name')||'').trim();a.reference=String(f.get('reference')||'').trim();a.course=String(f.get('course')||'').trim();a.startDate=String(f.get('startDate')||'');a.endDate=String(f.get('endDate')||'');a.taughtAreas=cleanList(f.get('taught'));a.targets=cleanList(f.get('targets'));const i=state.apprentices.findIndex(x=>x.id===a.id);if(i>=0)state.apprentices[i]=a;else state.apprentices.push(a);currentId=a.id;save();toast('Apprentice saved');renderApprentice(a.id)};$('[data-delete]')?.addEventListener('click',()=>{if(!confirm(`Delete ${a.name}?`))return;state.apprentices=state.apprentices.filter(x=>x.id!==a.id);state.learning=state.learning.filter(x=>x.apprenticeId!==a.id);state.witnesses=state.witnesses.filter(x=>x.apprenticeId!==a.id);state.oneToOnes=state.oneToOnes.filter(x=>x.apprenticeId!==a.id);state.actions=state.actions.filter(x=>x.apprenticeId!==a.id);save();renderApprentices();toast('Apprentice deleted')})}
function renderApprentice(id){const a=getApprentice(id);if(!a)return renderApprentices();currentId=id;const done=workplaceAreas(id),opp=opportunities(a),open=actionsFor(id).filter(x=>x.status!=='complete');openOverlay(a.name,'Workplace progress and what the employer can help with next.','APPRENTICE');content.innerHTML=`<div class="metric-grid"><div class="metric-card"><strong>${done.length}</strong><span>workplace areas</span></div><div class="metric-card"><strong>${opp.length}</strong><span>opportunities</span></div><div class="metric-card"><strong>${open.length}</strong><span>open actions</span></div></div><div class="section-head"><h2>Going well</h2><span>${marker()}</span></div><div class="card">${done.length?done.slice(0,8).map(x=>`<div class="focus-row"><div><strong>${esc(x)}</strong><small>Validated workplace activity/evidence exists</small></div><span class="chip good">Recorded</span></div>`).join(''):'<p>No employer/workplace evidence recorded yet.</p>'}</div><div class="section-head"><h2>Needs workplace experience</h2><span>from taught areas & targets</span></div><div class="card">${opp.length?opp.map(x=>`<div class="opportunity"><strong>${esc(x)}</strong><span>This has been identified but no workplace evidence is recorded yet.</span></div>`).join(''):'<p>No current workplace gaps identified from the information Tinos holds.</p>'}</div><div class="action-grid"><button class="action-card" data-a="learning"><strong>Record learning</strong><span>Add meaningful workplace learning and hours.</span></button><button class="action-card" data-a="witness"><strong>Witness evidence</strong><span>Record what you directly observed.</span></button><button class="action-card" data-a="one"><strong>1-to-1</strong><span>Quick development conversation and targets.</span></button><button class="action-card" data-a="actions"><strong>Progress & actions</strong><span>Plan workplace opportunities.</span></button><button class="action-card" data-a="share"><strong>Share update</strong><span>Create an Evia/Milos-ready data payload.</span></button><button class="action-card" data-a="edit"><strong>Edit apprentice</strong><span>Update course, taught areas or targets.</span></button></div>`;$$('[data-a]').forEach(b=>b.onclick=()=>{const v=b.dataset.a;if(v==='learning')learningForm(id);if(v==='witness')witnessForm(id);if(v==='one')oneToOneForm(id);if(v==='actions')renderApprenticeActions(id);if(v==='share')renderExchange('export',id);if(v==='edit')apprenticeForm(a)})}

function renderLearning(){openOverlay('Workplace Learning','Record learning that genuinely developed occupational knowledge, skills or behaviours. Confirmation verifies the activity happened; it does not award competence.');content.innerHTML=`<div class="button-row"><button class="primary" data-add-learning ${state.apprentices.length?'':'disabled'}>+ Record learning</button></div>${state.learning.length?`<div class="list">${state.learning.map(r=>{const a=getApprentice(r.apprenticeId);return `<button class="list-button" data-learning="${r.id}"><span class="list-copy"><strong>${esc(r.activity)}</strong><span>${esc(a?.name||'Unknown')} · ${fmt(r.date)} · ${Number(r.hours||0).toFixed(1)}h</span></span><span class="chip good">Confirmed</span></button>`}).join('')}</div>`:`<div class="empty"><strong>No workplace learning yet</strong><span>Add learning when something genuinely develops the apprentice beyond routine productive work.</span></div>`}`;$('[data-add-learning]')?.addEventListener('click',()=>learningForm(currentId||state.apprentices[0]?.id));$$('[data-learning]').forEach(b=>b.onclick=()=>renderLearningRecord(b.dataset.learning))}
function apprenticeOptions(selected){return state.apprentices.map(a=>`<option value="${a.id}" ${a.id===selected?'selected':''}>${esc(a.name)}</option>`).join('')}
function learningForm(id){if(!state.apprentices.length)return renderApprentices();const a=getApprentice(id)||state.apprentices[0];openOverlay('Record workplace learning',`For ${a.name}. Tinos will keep employer confirmation separate from assessor judgement.`,'LEARNING');content.innerHTML=`<form id="learningForm"><div class="card"><div class="form-grid"><label class="field full"><span>Apprentice</span><select name="apprentice">${apprenticeOptions(a.id)}</select></label><label class="field"><span>Date</span><input type="date" name="date" value="${today()}"></label><label class="field"><span>Learning time (hours)</span><input type="number" min="0" step="0.25" name="hours" value="1"></label><label class="field full"><span>Activity</span><input name="activity" placeholder="e.g. Setting out a cavity wall" required></label><label class="field full"><span>What did the apprentice learn or practise?</span><textarea name="learning" required></textarea></label><label class="field full"><span>Relevant course areas / KSBs / ACs</span><textarea name="areas" placeholder="Use plain-language task areas or formal codes"></textarea></label><label class="field full"><span>Employer confirmation</span><select name="confirmation"><option value="confirmed">I can confirm this activity took place</option><option value="not-confirmed">I cannot confirm this activity</option></select></label></div></div><div class="button-row"><button class="primary">Save learning</button></div></form>`;$('#learningForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),rec={id:uid(),apprenticeId:String(f.get('apprentice')),date:String(f.get('date')||today()),hours:Math.max(0,Number(f.get('hours')||0)),activity:String(f.get('activity')||'').trim(),learning:String(f.get('learning')||'').trim(),areas:cleanList(f.get('areas')),confirmation:String(f.get('confirmation')),source:'tinos',createdAt:new Date().toISOString()};state.learning.unshift(rec);save();toast('Workplace learning saved');renderLearningRecord(rec.id)}}
function renderLearningRecord(id){const r=state.learning.find(x=>x.id===id);if(!r)return renderLearning();const a=getApprentice(r.apprenticeId);openOverlay(r.activity,`${a?.name||'Apprentice'} · ${fmt(r.date)}`,'WORKPLACE LEARNING');content.innerHTML=`<div class="card"><h3>Learning / practice</h3><p>${esc(r.learning)}</p></div><div class="card"><h3>Relevant areas</h3><p>${r.areas.length?r.areas.map(esc).join(' · '):'None mapped yet.'}</p>${marker()}</div><div class="card"><h3>Employer confirmation</h3><p>${r.confirmation==='confirmed'?'Employer confirmed that this activity took place.':'Employer could not confirm this activity.'}</p><p class="muted">This confirmation is evidence provenance, not an assessor competence decision.</p></div>`}

function renderWitnesses(){openOverlay('Witness Evidence','Capture what the employer directly observed. The orange marker shows validated workplace evidence exists; it does not automatically mean the criterion is achieved.');content.innerHTML=`<div class="button-row"><button class="primary" data-add-witness ${state.apprentices.length?'':'disabled'}>+ Add witness evidence</button></div>${state.witnesses.length?`<div class="list">${state.witnesses.map(r=>{const a=getApprentice(r.apprenticeId);return `<button class="list-button" data-witness="${r.id}"><span class="list-copy"><strong>${esc(r.task)}</strong><span>${esc(a?.name||'Unknown')} · ${fmt(r.date)} · rating ${r.rating}/3</span></span><span class="chip">Witness</span></button>`}).join('')}</div>`:`<div class="empty"><strong>No witness evidence yet</strong><span>Use this when you directly observe the apprentice carrying out a task.</span></div>`}`;$('[data-add-witness]')?.addEventListener('click',()=>witnessForm(currentId||state.apprentices[0]?.id));$$('[data-witness]').forEach(b=>b.onclick=()=>renderWitnessRecord(b.dataset.witness))}
function witnessForm(id){if(!state.apprentices.length)return renderApprentices();const a=getApprentice(id)||state.apprentices[0];openOverlay('Witness evidence',`Record what you directly observed ${a.name} doing.`,'WITNESS');content.innerHTML=`<form id="witnessForm"><div class="card"><div class="form-grid"><label class="field full"><span>Apprentice</span><select name="apprentice">${apprenticeOptions(a.id)}</select></label><label class="field"><span>Date</span><input type="date" name="date" value="${today()}"></label><label class="field"><span>Rating</span><select name="rating"><option value="1">1 — Training required</option><option value="2">2 — Satisfactory</option><option value="3">3 — Competent</option></select></label><label class="field full"><span>Task observed</span><input name="task" required></label><label class="field full"><span>What did you observe?</span><textarea name="observed" required></textarea></label><label class="field full"><span>Quality / standard of work</span><textarea name="quality"></textarea></label><label class="field full"><span>Safety / controls followed</span><textarea name="safety"></textarea></label><label class="field full"><span>Independence / support needed</span><textarea name="independence"></textarea></label><label class="field full"><span>Relevant course areas / KSBs / ACs</span><textarea name="areas"></textarea></label><label class="field full"><span>Witness name / role</span><input name="signedBy" value="${esc(state.settings.employerName||'')}"></label></div></div><div class="button-row"><button class="primary">Save witness evidence</button></div></form>`;$('#witnessForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),rec={id:uid(),apprenticeId:String(f.get('apprentice')),date:String(f.get('date')||today()),rating:Number(f.get('rating')||1),task:String(f.get('task')||'').trim(),observed:String(f.get('observed')||'').trim(),quality:String(f.get('quality')||'').trim(),safety:String(f.get('safety')||'').trim(),independence:String(f.get('independence')||'').trim(),areas:cleanList(f.get('areas')),signedBy:String(f.get('signedBy')||'').trim(),source:'tinos',verified:true,createdAt:new Date().toISOString()};state.witnesses.unshift(rec);save();toast('Witness evidence saved');renderWitnessRecord(rec.id)}}
function renderWitnessRecord(id){const r=state.witnesses.find(x=>x.id===id);if(!r)return renderWitnesses();const a=getApprentice(r.apprenticeId);openOverlay(r.task,`${a?.name||'Apprentice'} · ${fmt(r.date)} · employer witness`,'WITNESS');content.innerHTML=`<div class="metric-grid"><div class="metric-card"><strong>${r.rating}/3</strong><span>${r.rating===1?'Training required':r.rating===2?'Satisfactory':'Competent'}</span></div><div class="metric-card"><strong>${r.areas.length}</strong><span>mapped areas</span></div><div class="metric-card"><strong>🔸</strong><span>workplace source</span></div></div><div class="card"><h3>Observed</h3><p>${esc(r.observed)}</p></div><div class="card"><h3>Quality</h3><p>${esc(r.quality||'Not recorded.')}</p><h3 style="margin-top:12px">Safety</h3><p>${esc(r.safety||'Not recorded.')}</p><h3 style="margin-top:12px">Independence</h3><p>${esc(r.independence||'Not recorded.')}</p></div><div class="card"><h3>Relevant course areas</h3><p>${r.areas.length?r.areas.map(esc).join(' · '):'None mapped yet.'}</p>${marker()}<p class="muted">A witness rating is the employer's workplace judgement. Final assessment/competence decisions remain with the appropriate assessor.</p></div><div class="card"><h3>Witness</h3><p>${esc(r.signedBy||'Not recorded')}</p></div>`}

function renderOneToOnes(){openOverlay('1-to-1s','Short employer conversations that capture development, concerns and workplace targets without turning into a long education form.');content.innerHTML=`<div class="button-row"><button class="primary" data-add-one ${state.apprentices.length?'':'disabled'}>+ Start 1-to-1</button></div>${state.oneToOnes.length?`<div class="list">${state.oneToOnes.map(r=>{const a=getApprentice(r.apprenticeId);return `<button class="list-button" data-one="${r.id}"><span class="list-copy"><strong>${esc(a?.name||'Unknown')}</strong><span>${fmt(r.date)} · ${esc(r.summary||'Employer 1-to-1')}</span></span><span class="chip">1-to-1</span></button>`}).join('')}</div>`:`<div class="empty"><strong>No 1-to-1s yet</strong><span>Use a quick 1-to-1 to record development and set workplace targets.</span></div>`}`;$('[data-add-one]')?.addEventListener('click',()=>oneToOneForm(currentId||state.apprentices[0]?.id));$$('[data-one]').forEach(b=>b.onclick=()=>renderOneRecord(b.dataset.one))}
function oneToOneForm(id){if(!state.apprentices.length)return renderApprentices();const a=getApprentice(id)||state.apprentices[0];openOverlay('Employer 1-to-1',`A quick development conversation with ${a.name}.`,'1-TO-1');content.innerHTML=`<form id="oneForm"><div class="card"><div class="form-grid"><label class="field full"><span>Apprentice</span><select name="apprentice">${apprenticeOptions(a.id)}</select></label><label class="field"><span>Date</span><input type="date" name="date" value="${today()}"></label><label class="field"><span>Overall progress</span><select name="progress"><option>Going well</option><option>Some development needed</option><option>Concern</option></select></label><label class="field full"><span>What is going well?</span><textarea name="well"></textarea></label><label class="field full"><span>Behaviour / reliability / attendance</span><textarea name="behaviour"></textarea></label><label class="field full"><span>Health & safety</span><textarea name="safety"></textarea></label><label class="field full"><span>Skills or knowledge to improve</span><textarea name="improve"></textarea></label><label class="field full"><span>New opportunities / responsibilities</span><textarea name="opportunities"></textarea></label><label class="field full"><span>Concerns</span><textarea name="concerns"></textarea></label><label class="field full"><span>Targets before next 1-to-1</span><textarea name="targets"></textarea></label></div></div><div class="button-row"><button class="primary">Save 1-to-1</button></div></form>`;$('#oneForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),apprenticeId=String(f.get('apprentice')),targets=cleanList(f.get('targets')),rec={id:uid(),apprenticeId,date:String(f.get('date')||today()),progress:String(f.get('progress')),well:String(f.get('well')||'').trim(),behaviour:String(f.get('behaviour')||'').trim(),safety:String(f.get('safety')||'').trim(),improve:String(f.get('improve')||'').trim(),opportunities:String(f.get('opportunities')||'').trim(),concerns:String(f.get('concerns')||'').trim(),targets,summary:String(f.get('progress')),createdAt:new Date().toISOString()};state.oneToOnes.unshift(rec);targets.forEach(t=>state.actions.unshift({id:uid(),apprenticeId,title:t,dueDate:'',status:'open',source:'1-to-1',createdAt:new Date().toISOString()}));save();toast('1-to-1 saved');renderOneRecord(rec.id)}}
function renderOneRecord(id){const r=state.oneToOnes.find(x=>x.id===id);if(!r)return renderOneToOnes();const a=getApprentice(r.apprenticeId);openOverlay('Employer 1-to-1',`${a?.name||'Apprentice'} · ${fmt(r.date)}`,'1-TO-1');content.innerHTML=`<div class="card"><h3>Overall progress</h3><p>${esc(r.progress)}</p></div>${[['Going well',r.well],['Behaviour / reliability / attendance',r.behaviour],['Health & safety',r.safety],['Needs improvement',r.improve],['New opportunities / responsibilities',r.opportunities],['Concerns',r.concerns],['Targets',r.targets?.join(' · ')]].map(([h,v])=>`<div class="card"><h3>${h}</h3><p>${esc(v||'Not recorded.')}</p></div>`).join('')}`}

function renderActions(){openOverlay('Progress & Actions','Focus on what the employer can actually do next, not just a percentage.');if(!state.apprentices.length){content.innerHTML='<div class="empty"><strong>No apprentices yet</strong><span>Add an apprentice to identify workplace opportunities.</span></div>';return}content.innerHTML=`<div class="list">${state.apprentices.map(a=>{const opp=opportunities(a),open=actionsFor(a.id).filter(x=>x.status!=='complete');return `<button class="list-button" data-actions="${a.id}"><span class="list-copy"><strong>${esc(a.name)}</strong><span>${opp.length} workplace opportunities · ${open.length} open actions</span></span><span class="chip warn">Review</span></button>`}).join('')}</div>`;$$('[data-actions]').forEach(b=>b.onclick=()=>renderApprenticeActions(b.dataset.actions))}
function renderApprenticeActions(id){const a=getApprentice(id);if(!a)return renderActions();currentId=id;const done=workplaceAreas(id),opp=opportunities(a),acts=actionsFor(id);openOverlay(`${a.name} · Progress & Actions`,'What is strong, what is missing and what the employer can help happen next.','PROGRESS');content.innerHTML=`<div class="section-head"><h2>Going well</h2><span>workplace evidence</span></div><div class="card">${done.length?done.slice(0,8).map(x=>`<div class="focus-row"><div><strong>${esc(x)}</strong><small>Employer/workplace evidence recorded</small></div><span class="chip good">🔸</span></div>`).join(''):'<p>No validated workplace areas recorded yet.</p>'}</div><div class="section-head"><h2>Recently taught / needs experience</h2><span>opportunities</span></div><div class="card">${opp.length?opp.map(x=>`<div class="opportunity"><strong>${esc(x)}</strong><span>Could this apprentice practise this at work?</span><div class="button-row"><button class="secondary" data-plan-opportunity="${esc(x)}">Plan this</button></div></div>`).join(''):'<p>No current opportunities identified.</p>'}</div><div class="section-head"><h2>Employer actions</h2><span>${acts.filter(x=>x.status!=='complete').length} open</span></div><div class="card">${acts.length?acts.map(x=>`<div class="focus-row"><div><strong>${esc(x.title)}</strong><small>${esc(x.source||'Employer action')}${x.dueDate?' · due '+fmt(x.dueDate):''}</small></div><button class="secondary" data-toggle-action="${x.id}">${x.status==='complete'?'Reopen':'Complete'}</button></div>`).join(''):'<p>No employer actions yet.</p>'}<div class="button-row"><button class="primary" data-add-action>+ Add action</button></div></div>`;$$('[data-plan-opportunity]').forEach(b=>b.onclick=()=>{state.actions.unshift({id:uid(),apprenticeId:id,title:`Give workplace opportunity: ${b.dataset.planOpportunity}`,dueDate:'',status:'open',source:'Tinos opportunity',createdAt:new Date().toISOString()});save();toast('Workplace opportunity planned');renderApprenticeActions(id)});$$('[data-toggle-action]').forEach(b=>b.onclick=()=>{const x=state.actions.find(y=>y.id===b.dataset.toggleAction);if(x)x.status=x.status==='complete'?'open':'complete';save();renderApprenticeActions(id)});$('[data-add-action]').onclick=()=>actionForm(id)}
function actionForm(id){const a=getApprentice(id);openOverlay('Add employer action',a?.name||'Apprentice','ACTION');content.innerHTML=`<form id="actionForm"><div class="card"><div class="form-grid"><label class="field full"><span>Action</span><input name="title" required></label><label class="field"><span>Due date</span><input type="date" name="dueDate"></label><label class="field"><span>Source</span><select name="source"><option>Employer</option><option>Review</option><option>College request</option><option>Assessor request</option></select></label></div></div><div class="button-row"><button class="primary">Save action</button></div></form>`;$('#actionForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.actions.unshift({id:uid(),apprenticeId:id,title:String(f.get('title')||'').trim(),dueDate:String(f.get('dueDate')||''),status:'open',source:String(f.get('source')||'Employer'),createdAt:new Date().toISOString()});save();toast('Action saved');renderApprenticeActions(id)}}

function exchangePayload(id){const a=getApprentice(id);if(!a)return null;return {schema:'nisia-event-bundle-v1',sourceApp:'Tinos',sourceRole:'employer',createdAt:new Date().toISOString(),apprentice:{reference:a.reference||'',course:a.course||''},workplaceLearning:learningFor(id),witnessEvidence:witnessFor(id),oneToOnes:oneToOnesFor(id),actions:actionsFor(id),workplaceAreas:workplaceAreas(id),marker:'orange-diamond'}}
function renderExchange(mode='home',id=currentId){openOverlay('Share / Scan','Tinos uses a structured Nisia-style payload so QR and future automatic sync can carry the same underlying records.','EXCHANGE');if(mode==='export'&&id){const a=getApprentice(id),payload=exchangePayload(id),text=JSON.stringify(payload);content.innerHTML=`<div class="card"><h3>Share update for ${esc(a?.name||'apprentice')}</h3><p>This payload contains workplace records and references, not a competence decision.</p></div><textarea class="code-box" id="payloadText" readonly>${esc(text)}</textarea><div class="button-row"><button class="primary" data-copy>Copy payload</button><button class="secondary" data-back-exchange>Back</button></div>`;$('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(text);toast('Payload copied')}catch{toast('Copy not available')}};$('[data-back-exchange]').onclick=()=>renderExchange();return}if(mode==='import'){content.innerHTML=`<div class="card"><h3>Import Evia / Nisia update</h3><p>Paste the decoded QR payload here. Tinos will only use the fields relevant to the employer.</p></div><form id="importForm"><label class="field full"><span>Payload</span><textarea name="payload" class="code-box" required></textarea></label><div class="button-row"><button class="primary">Import update</button></div></form>`;$('#importForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const data=JSON.parse(String(f.get('payload')||''));importUpdate(data);toast('Update imported');renderApprentices()}catch{toast('That payload could not be read')}};return}content.innerHTML=`<div class="action-grid"><button class="action-card" data-ex="import"><strong>Scan / import</strong><span>Import a decoded QR/Nisia payload from Evia, Symi or Milos.</span></button><button class="action-card" data-ex="export"><strong>Share apprentice update</strong><span>Create the structured payload Evia/Milos can use.</span></button></div><div class="card"><h3>QR transport</h3><p>The data contract is ready for QR transport. This first Tinos build stores and validates the structured payload locally; camera QR encoding/decoding can sit on top without changing the record format.</p></div>`;$$('[data-ex]').forEach(b=>b.onclick=()=>{if(b.dataset.ex==='import')renderExchange('import');else chooseExport()})}
function chooseExport(){if(!state.apprentices.length)return renderApprentices();openOverlay('Choose apprentice','Create a shareable workplace update.','EXCHANGE');content.innerHTML=`<div class="list">${state.apprentices.map(a=>`<button class="list-button" data-export="${a.id}"><span class="list-copy"><strong>${esc(a.name)}</strong><span>${esc(a.course||'Course not added')}</span></span><span class="chip">Share</span></button>`).join('')}</div>`;$$('[data-export]').forEach(b=>b.onclick=()=>renderExchange('export',b.dataset.export))}
function importUpdate(data){const ref=String(data?.apprentice?.reference||data?.learner?.reference||'').trim(),course=String(data?.apprentice?.course||data?.learner?.course||'').trim(),name=String(data?.apprentice?.name||data?.learner?.name||'Imported apprentice').trim();let a=ref?state.apprentices.find(x=>x.reference===ref):null;if(!a){a={id:uid(),name,reference:ref,course,startDate:'',endDate:'',progress:null,taughtAreas:[],assessedAreas:[],targets:[]};state.apprentices.push(a)}if(course)a.course=course;a.taughtAreas=uniq([...(a.taughtAreas||[]),...(data.taughtAreas||data.coveredAreas||[])]);a.assessedAreas=uniq([...(a.assessedAreas||[]),...(data.assessedAreas||[])]);a.targets=uniq([...(a.targets||[]),...(data.targets||[])]);state.updates.unshift({id:uid(),apprenticeId:a.id,receivedAt:new Date().toISOString(),sourceApp:String(data.sourceApp||'Unknown'),payload:data});save()}

function renderSettings(){openOverlay('Settings','Employer details used in Tinos records.','SETTINGS');content.innerHTML=`<form id="settingsForm"><div class="card"><div class="form-grid"><label class="field full"><span>Your name</span><input name="employerName" value="${esc(state.settings.employerName||'')}"></label><label class="field full"><span>Company / workplace</span><input name="company" value="${esc(state.settings.company||'')}"></label></div></div><div class="card"><h3>Data</h3><p>Tinos stores this first build locally on this device. No learner data is written into the public GitHub repository.</p></div><div class="button-row"><button class="primary">Save settings</button></div></form>`;$('#settingsForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.settings.employerName=String(f.get('employerName')||'').trim();state.settings.company=String(f.get('company')||'').trim();save();toast('Settings saved');greeting()}}

function globalClick(e){const open=e.target.closest('[data-open]');if(open)openView(open.dataset.open)}
menu.onclick=()=>{const open=!tools.classList.contains('open');tools.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open))};tools.onclick=globalClick;document.querySelector('.bottom-arches').onclick=globalClick;pillStack.onclick=globalClick;$('#overlayClose').onclick=closeOverlay;back.onclick=()=>overlay.classList.contains('open')?closeOverlay():deactivate();$('#tinosStage').onclick=()=>screen.classList.contains('active')?deactivate():activate();$('#centreMark').onclick=()=>screen.classList.contains('active')?deactivate():activate();$('#tinosStage').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();screen.classList.contains('active')?deactivate():activate()}};
setInterval(blink,4200);homeMetrics();greeting();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
})();
